import {
  User,
  Department,
  Office,
  AcademicOrganization,
  NonAcademicOrganization,
  ClearanceRequest,
  Announcement,
  Notification,
  ActivityLog,
} from "./types";

// Current User based on role
export const mockUsers: Record<string, User> = {
  student: {
    id: "usr_001",
    email: "juan.delacruz@cjc.edu.ph",
    firstName: "Juan",
    lastName: "Dela Cruz",
    middleName: "Santos",
    role: "student",
    studentId: "2021-00001",
    course: "Bachelor of Science in Information Technology",
    yearLevel: "4th Year",
  },
  office: {
    id: "usr_002",
    email: "maria.santos@cjc.edu.ph",
    firstName: "Maria",
    lastName: "Santos",
    role: "office",
    department: "Library",
    position: "Library Staff",
  },
  "academic-club": {
    id: "usr_003",
    email: "jose.reyes@cjc.edu.ph",
    firstName: "Jose",
    lastName: "Reyes",
    role: "academic-club",
    department: "IT Society",
    position: "President",
  },
  "non-academic-club": {
    id: "usr_006",
    email: "anna.cruz@cjc.edu.ph",
    firstName: "Anna",
    lastName: "Cruz",
    role: "non-academic-club",
    department: "Supreme Student Council",
    position: "Secretary",
  },
  admin: {
    id: "usr_005",
    email: "admin@cjc.edu.ph",
    firstName: "System",
    lastName: "Administrator",
    role: "admin",
    position: "IT Administrator",
  },
};

// Departments (Colleges) - Admin manages these
export const departments: Department[] = [
  {
    id: "dept_001",
    name: "College of Computing and Information Sciences",
    code: "CCIS",
    description: "Information Technology, Computer Science, and Information Systems programs",
    head: "Dr. Roberto Lopez",
  },
];

// Offices - These handle clearance approvals
export const offices: Office[] = [
  {
    id: "office_001",
    name: "Library",
    code: "LIB",
    description: "Book returns and library card clearance",
    head: "Mrs. Maria Santos",
  },
  {
    id: "office_002",
    name: "Finance Office",
    code: "FIN",
    description: "Tuition and other fees payment verification",
    head: "Mr. Pedro Reyes",
  },
  {
    id: "office_003",
    name: "Registrar",
    code: "REG",
    description: "Academic records and enrollment verification",
    head: "Ms. Ana Garcia",
  },
  {
    id: "office_004",
    name: "Student Affairs Office",
    code: "SAO",
    description: "Student discipline and organization clearance",
    head: "Mr. Jose Cruz",
  },
  {
    id: "office_005",
    name: "Guidance Office",
    code: "GUID",
    description: "Exit interview and counseling clearance",
    head: "Mrs. Elena Mendoza",
  },
  {
    id: "office_006",
    name: "Clinic",
    code: "CLIN",
    description: "Medical clearance and health records",
    head: "Dr. Carmen Rivera",
  },
];

// Academic Organizations - Course-related clubs (require clearance)
export const academicOrganizations: AcademicOrganization[] = [
  {
    id: "acad_org_001",
    name: "IT Society",
    code: "ITS",
    description: "Organization for BS Information Technology students",
    adviser: "Mr. Juan Reyes",
    department: "CCIS",
  },
  {
    id: "acad_org_002",
    name: "Computer Science Society",
    code: "CSS",
    description: "Organization for BS Computer Science students",
    adviser: "Ms. Maria Lopez",
    department: "CCIS",
  },
  {
    id: "acad_org_003",
    name: "Information Systems Guild",
    code: "ISG",
    description: "Organization for BS Information Systems students",
    adviser: "Mr. Pedro Santos",
    department: "CCIS",
  },
];

// Non-Academic Organizations - General clubs (require clearance)
export const nonAcademicOrganizations: NonAcademicOrganization[] = [
  {
    id: "non_acad_001",
    name: "Supreme Student Council",
    code: "SSC",
    description: "Main student government body of the institution",
    adviser: "Dr. Ana Garcia",
  },
  {
    id: "non_acad_002",
    name: "CCIS Student Council",
    code: "CCIS-SC",
    description: "Student council for CCIS department",
    adviser: "Mr. Jose Cruz",
  },
  {
    id: "non_acad_003",
    name: "Red Cross Youth",
    code: "RCY",
    description: "Humanitarian volunteer organization",
    adviser: "Mrs. Carmen Rivera",
  },
  {
    id: "non_acad_004",
    name: "Peer Facilitators",
    code: "PF",
    description: "Student mentoring and guidance organization",
    adviser: "Mrs. Elena Mendoza",
  },
];

export const mockStudents: User[] = [
  {
    id: "std_001",
    email: "juan.delacruz@cjc.edu.ph",
    firstName: "Juan",
    lastName: "Dela Cruz",
    role: "student",
    studentId: "2021-00001",
    course: "BSIT",
    yearLevel: "4th Year",
  },
  {
    id: "std_002",
    email: "maria.santos@cjc.edu.ph",
    firstName: "Maria",
    lastName: "Santos",
    role: "student",
    studentId: "2021-00002",
    course: "BSCS",
    yearLevel: "4th Year",
  },
  {
    id: "std_003",
    email: "pedro.reyes@cjc.edu.ph",
    firstName: "Pedro",
    lastName: "Reyes",
    role: "student",
    studentId: "2022-00015",
    course: "BSIT",
    yearLevel: "3rd Year",
  },
  {
    id: "std_004",
    email: "ana.garcia@cjc.edu.ph",
    firstName: "Ana",
    lastName: "Garcia",
    role: "student",
    studentId: "2022-00023",
    course: "BSIS",
    yearLevel: "3rd Year",
  },
  {
    id: "std_005",
    email: "carlos.mendoza@cjc.edu.ph",
    firstName: "Carlos",
    lastName: "Mendoza",
    role: "student",
    studentId: "2023-00045",
    course: "BSIT",
    yearLevel: "2nd Year",
  },
];

export const mockClearanceRequests: ClearanceRequest[] = [
  {
    id: "clr_001",
    studentId: "2021-00001",
    studentName: "Juan Dela Cruz",
    studentCourse: "BSIT",
    studentYear: "4th Year",
    academicYear: "2024-2025",
    semester: "2nd Semester",
    type: "semester",
    status: "in_progress",
    progress: 67,
    items: [
      {
        id: "item_001",
        departmentId: "dept_001",
        departmentName: "Library",
        status: "approved",
        approvedBy: "Mrs. Santos",
        approvedAt: "2024-01-15T10:30:00Z",
      },
      {
        id: "item_002",
        departmentId: "dept_002",
        departmentName: "Finance Office",
        status: "approved",
        approvedBy: "Mr. Reyes",
        approvedAt: "2024-01-16T14:20:00Z",
      },
      {
        id: "item_003",
        departmentId: "dept_003",
        departmentName: "Registrar",
        status: "pending",
      },
      {
        id: "item_004",
        departmentId: "dept_004",
        departmentName: "Student Affairs",
        status: "approved",
        approvedBy: "Mr. Cruz",
        approvedAt: "2024-01-14T09:00:00Z",
      },
      {
        id: "item_005",
        departmentId: "dept_005",
        departmentName: "CCIS Department",
        status: "pending",
      },
      {
        id: "item_006",
        departmentId: "dept_006",
        departmentName: "Guidance Office",
        status: "approved",
        approvedBy: "Mrs. Mendoza",
        approvedAt: "2024-01-17T11:15:00Z",
      },
    ],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-17T11:15:00Z",
  },
  {
    id: "clr_002",
    studentId: "2021-00002",
    studentName: "Maria Santos",
    studentCourse: "BSCS",
    studentYear: "4th Year",
    academicYear: "2024-2025",
    semester: "2nd Semester",
    type: "graduation",
    status: "pending",
    progress: 33,
    items: [
      {
        id: "item_007",
        departmentId: "dept_001",
        departmentName: "Library",
        status: "approved",
        approvedBy: "Mrs. Santos",
        approvedAt: "2024-01-18T10:00:00Z",
      },
      {
        id: "item_008",
        departmentId: "dept_002",
        departmentName: "Finance Office",
        status: "on_hold",
        remarks: "Pending payment verification",
      },
      {
        id: "item_009",
        departmentId: "dept_003",
        departmentName: "Registrar",
        status: "pending",
      },
      {
        id: "item_010",
        departmentId: "dept_004",
        departmentName: "Student Affairs",
        status: "pending",
      },
      {
        id: "item_011",
        departmentId: "dept_005",
        departmentName: "CCIS Department",
        status: "approved",
        approvedBy: "Dr. Lopez",
        approvedAt: "2024-01-19T14:30:00Z",
      },
      {
        id: "item_012",
        departmentId: "dept_006",
        departmentName: "Guidance Office",
        status: "pending",
      },
    ],
    createdAt: "2024-01-12T09:30:00Z",
    updatedAt: "2024-01-19T14:30:00Z",
  },
  {
    id: "clr_003",
    studentId: "2022-00015",
    studentName: "Pedro Reyes",
    studentCourse: "BSIT",
    studentYear: "3rd Year",
    academicYear: "2024-2025",
    semester: "2nd Semester",
    type: "semester",
    status: "completed",
    progress: 100,
    items: [
      {
        id: "item_013",
        departmentId: "dept_001",
        departmentName: "Library",
        status: "approved",
        approvedBy: "Mrs. Santos",
        approvedAt: "2024-01-10T10:00:00Z",
      },
      {
        id: "item_014",
        departmentId: "dept_002",
        departmentName: "Finance Office",
        status: "approved",
        approvedBy: "Mr. Reyes",
        approvedAt: "2024-01-11T11:00:00Z",
      },
      {
        id: "item_015",
        departmentId: "dept_003",
        departmentName: "Registrar",
        status: "approved",
        approvedBy: "Ms. Garcia",
        approvedAt: "2024-01-12T09:00:00Z",
      },
      {
        id: "item_016",
        departmentId: "dept_004",
        departmentName: "Student Affairs",
        status: "approved",
        approvedBy: "Mr. Cruz",
        approvedAt: "2024-01-13T14:00:00Z",
      },
      {
        id: "item_017",
        departmentId: "dept_005",
        departmentName: "CCIS Department",
        status: "approved",
        approvedBy: "Dr. Lopez",
        approvedAt: "2024-01-14T16:00:00Z",
      },
      {
        id: "item_018",
        departmentId: "dept_006",
        departmentName: "Guidance Office",
        status: "approved",
        approvedBy: "Mrs. Mendoza",
        approvedAt: "2024-01-15T10:30:00Z",
      },
    ],
    createdAt: "2024-01-08T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
];

export const announcements: Announcement[] = [
  {
    id: "ann_001",
    title: "Clearance Deadline Extended",
    content: "The deadline for 2nd semester clearance has been extended to February 28, 2025. Please complete all requirements before the deadline.",
    author: "Registrar Office",
    priority: "high",
    createdAt: "2024-01-20T08:00:00Z",
  },
  {
    id: "ann_002",
    title: "Library Hours Update",
    content: "The library will be open from 7:00 AM to 7:00 PM during clearance week. Please return all borrowed books.",
    author: "Library",
    priority: "normal",
    createdAt: "2024-01-19T10:00:00Z",
  },
  {
    id: "ann_003",
    title: "Finance Office Payment Reminder",
    content: "Students with pending balances must settle their accounts before clearance approval. Visit the Finance Office for payment arrangements.",
    author: "Finance Office",
    priority: "urgent",
    createdAt: "2024-01-18T14:00:00Z",
  },
  {
    id: "ann_004",
    title: "Graduation Clearance Requirements",
    content: "Graduating students must submit additional requirements including exit interview form and alumni registration.",
    author: "Student Affairs",
    priority: "high",
    createdAt: "2024-01-17T09:00:00Z",
  },
  {
    id: "ann_005",
    title: "System Maintenance Notice",
    content: "The clearance system will undergo maintenance on January 25, 2025 from 12:00 AM to 4:00 AM. Please save your work.",
    author: "IT Department",
    priority: "normal",
    createdAt: "2024-01-16T16:00:00Z",
  },
];

export const notifications: Notification[] = [
  {
    id: "notif_001",
    userId: "usr_001",
    title: "Clearance Approved",
    message: "Your Library clearance has been approved by Mrs. Santos.",
    type: "success",
    isRead: false,
    createdAt: "2024-01-15T10:30:00Z",
    link: "/student/clearance/clr_001",
  },
  {
    id: "notif_002",
    userId: "usr_001",
    title: "Action Required",
    message: "Please submit your exit interview form to the Guidance Office.",
    type: "warning",
    isRead: false,
    createdAt: "2024-01-14T14:00:00Z",
    link: "/student/clearance/clr_001",
  },
  {
    id: "notif_003",
    userId: "usr_001",
    title: "Finance Clearance Approved",
    message: "Your Finance Office clearance has been approved by Mr. Reyes.",
    type: "success",
    isRead: true,
    createdAt: "2024-01-16T14:20:00Z",
    link: "/student/clearance/clr_001",
  },
];

export const activityLog: ActivityLog[] = [
  {
    id: "act_001",
    userId: "usr_002",
    userName: "Mrs. Santos",
    userRole: "office",
    action: "approved",
    details: "Approved library clearance for Juan Dela Cruz (2021-00001)",
    targetType: "clearance",
    targetId: "clr_001",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "act_002",
    userId: "usr_003",
    userName: "Mr. Reyes",
    userRole: "office",
    action: "approved",
    details: "Approved finance clearance for Juan Dela Cruz (2021-00001)",
    targetType: "clearance",
    targetId: "clr_001",
    createdAt: "2024-01-16T14:20:00Z",
  },
  {
    id: "act_003",
    userId: "std_001",
    userName: "Juan Dela Cruz",
    userRole: "student",
    action: "submitted",
    details: "Submitted clearance request for 2nd Semester 2024-2025",
    targetType: "clearance",
    targetId: "clr_001",
    createdAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "act_004",
    userId: "usr_004",
    userName: "Jose Reyes",
    userRole: "academic-club",
    action: "approved",
    details: "Approved IT Society clearance for Maria Santos (2021-00002)",
    targetType: "clearance",
    targetId: "clr_002",
    createdAt: "2024-01-19T14:30:00Z",
  },
  {
    id: "act_005",
    userId: "usr_002",
    userName: "Mrs. Santos",
    userRole: "office",
    action: "put_on_hold",
    details: "Put on hold: Finance clearance for Maria Santos - Pending payment verification",
    targetType: "clearance",
    targetId: "clr_002",
    createdAt: "2024-01-18T11:00:00Z",
  },
];

export const dashboardStats = {
  totalStudents: 5234,
  pendingRequests: 342,
  approvedToday: 56,
  completionRate: 87.5,
};
